### ISSUE TITLE
Inability to assign policy from "nested" module

### ISSUE THREAD

**Issue by GoodDingo** [Azure/terraform-azurerm-caf-enterprise-scale#152]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: `1.0.5`

**azure provider**: `2.73.0`

**module**: `0.4.0`

----

### Description

**When deploying module in several steps and keeping all policy definitions in parent MG, I'm unable to attach those custom policies in nested module.**

I'm deploying ESLZ in several stages.
1) basic module deployment with several policy exclusions and custom policy initiative for tagging
2) this gets deployed correctly, policy lives under top MG, all is good
3) then I want to deploy just 2 new MG implemented using calling module twice with `deploy_core_landing_zones = false`
4) here during the deployment everything falls apart

<details>
  <summary>code for `main.tf`</summary>

```hcl
# main.tf

data "azurerm_client_config" "current" {}

module "enterprise_scale" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.4.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm.connectivity
    azurerm.management   = azurerm.management
  }

  root_parent_id = data.azurerm_client_config.current.tenant_id
  root_id        = var.root_id
  root_name      = var.root_name
  library_path   = "${path.root}/lib"
}

# plus there is a definition of custom Policy Initiative that gets deployed 
```

</details>

<details>
  <summary>code for `dependent.tf`</summary>

```hcl
# dependent.tf, it is NOT deployed in the same statefile, it is deployed in next statefile after the main is deployed
# hence no "depends_on enterprise_scale" is  here

module "eslz_team_cloudteam" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.4.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm.connectivity
    azurerm.management   = azurerm.management
  }

  root_parent_id            = "${var.root_id}-landing-zones"
  root_id                   = var.root_id
  deploy_core_landing_zones = false
  library_path              = "${path.root}/lib"

  custom_landing_zones = {
    "${var.root_id}-lz--cloudteam" = {
      display_name               = "${upper(var.root_id)} :: Cloud Team"
      parent_management_group_id = "${var.root_id}-landing-zones"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "default_empty"
        parameters     = {}
        access_control = {}
      }
    }
  }
}


module "eslz_team_cloudteam_dev" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "0.4.0"

  providers = {
    azurerm              = azurerm
    azurerm.connectivity = azurerm.connectivity
    azurerm.management   = azurerm.management
  }

  root_parent_id            = "${var.root_id}-lz--cloudteam"
  root_id                   = var.root_id
  deploy_core_landing_zones = false
  library_path              = "${path.root}/lib"

  custom_landing_zones = {
    "${var.root_id}-lz--cloudteam-dev" = {
      display_name               = "${upper(var.root_id)} :: Cloud Team - Dev"
      parent_management_group_id = "${var.root_id}-lz--cloudteam"
      subscription_ids           = []
      archetype_config = {
        archetype_id   = "generic_env_dev"    # <-- this triggers assignment
        parameters     = {}
        access_control = {}
      }
    }
  }

  depends_on = [
    module.eslz_team_cloudteam,
  ]
}

```
</details>

<details>
  <summary>code for policy assignement living in dependent `lib/`</summary>

```yaml
# lib/policy_assignments/policy_assignment_company_global_tagging.yaml

generic_env_dev:
  policy_assignments:
    - Deny-Resource-Locations  # this works
    - Company-Global-Tagging  # this fails, it is custom initiative living in root_id MG
  policy_definitions: []
  policy_set_definitions: []
  role_definitions: []
  archetype_config:
    parameters:
      Deny-Resource-Locations:
        listOfAllowedLocations:
          - eastus
          - westus
    access_control: {}
```

```yaml
# lib/policy_assignments/policy_assignment_company_global_tagging.yaml

name: Company-Global-Tagging
type: Microsoft.Authorization/policyAssignments
apiVersion: '2019-09-01'
properties:
  description: All resources should conform to global Company Tagging convention.
  displayName: Assign policies for Company Cloud Tagging.
  notScopes: []
  parameters: null

  # I've tried many things here, nothing worked for me
  policyDefinitionId: >-
    /providers/Microsoft.Management/managementgroups/cloud/providers/Microsoft.Authorization/policySetDefinitions/Company-Global-Tagging-Initiative
  scope: '${current_scope_resource_id}'
  enforcementMode: Default
location: '${default_location}'
identity:
  type: SystemAssigned
```
</details>

**Steps to Reproduce**

<details>
  <summary>Having those files in dependent dir:</summary>

```
├── lib
│   ├── archetype_definitions
│   │   └── archetype_definition_generic_env_dev.yml
│   └── policy_assignments
│       └── policy_assignment_company_global_tagging.yml
├── team_cloud.tf
├── terraform.tf
└── variables.tf
```
</details>

1. during `terraform plan` I'll get

```
│ Error: Invalid for_each argument
│
│   on .terraform/modules/eslz_team_cloudteam_dev/locals.policy_assignments.tf line 158, in data "azurerm_policy_definition" "external_lookup":
│  158:   for_each = local.azurerm_policy_definition_external_lookup
│     ├────────────────
│     │ local.azurerm_policy_definition_external_lookup will be known only after apply
│
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the
│ -target argument to first apply only the resources that the for_each depends on.
```

---

What I basically want is to define the Policy initiative once on the top MG and then assign it on leaf MG (the bug is about inability to do so, but maybe it's my fault).

Work-around is to define Policy Initiative many times, always on the leaf MG and assign it there, it works, but it feels wrong to have total same definition so many times.

Thank you very much with any guidance, I've tried everything that I know (which is very little to be frank).
Feel free to close this issue and maybe writing a wiki article how to do it correctly. :-)

Appreciate all your work, and very well thought out design. Kudos
