### ISSUE TITLE
Include sample pipeline files - suggesting Azure DevOps pipeline yml file in this issue

### ISSUE THREAD

**Issue by autocloudarc** [Azure/terraform-azurerm-caf-enterprise-scale#682]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

This feature request is to suggest a set of sample pipline files that can be referenced for use as a template to automate the deployment of landing zones using CI/CD with yml files (Azure DevOps CI/CD, GitHub Actions, Bitbucket, GitLab, etc). I have only tested this specifically with Azure DevOps Services so far, so for this issue, this is what I'm proposing.

#### Describe the solution you'd like

I'd like to suggest using a reference pipleine for Azure DevOps Services CI/CD deployment for those that use Azure DevOps to consider

```yml 
# Starter pipeline for Azure DevOps Services CI/CD deployment
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - main

parameters:
- name: terraformVersion
  type: string
  default: 1.4.2
- name: serviceName
  type: string
  default: <service-principal-name>
- name: TerraformDirectory
  type: string
  default: $(System.DefaultWorkingDirectory)
- name: commandOptions
  type: string
  default: '-out=$(System.DefaultWorkingDirectory)/terraform.tfplan'
- name: additionalParameters
  type: object
  default: []
- name: TerraformStateStorageAccountResourceGroupName
  type: string
  default: <resource-group-name>
- name: AzureRegion
  type: string
  default: <azure-region>
- name: TerraformStateStorageAccountName
  type: string
  default: <storage-account-name>
- name: TerraformStateStorageAccountContainerName
  type: string
  default: <storage-account-container-name>
- name: authSubscriptionId
  type: string
  default: <subscription-id-to-authorize-to>
- name: enviornment
  type: string
  default: dev

- name: rollback
  displayName: Rollback Deployment
  type: boolean      
  default: true 
  values:
    - true
    - false

jobs: 
- job: 'Terraform'
  displayName: 'Terraform'
  timeoutInMinutes: 180
  continueOnError: true
  cancelTimeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-latest'

  steps: 
  - checkout: self
    displayName: 'Checkout'
    fetchDepth: 0
    # https://stackoverflow.com/questions/59508121/no-url-found-for-submodule-path-in-gitmodules-error-in-azure-devops-build
    submodules: true
    lfs: true 
    persistCredentials: true

  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: install terraform
    inputs:
      terraformVersion: ${{ parameters.terraformVersion }}
  - task: TerraformCLI@0
    displayName: 'Terraform : init'
    inputs:
      command: init
      commandOptions: -reconfigure
      backendType: azurerm
      backendAzureRmSubscriptionId: ${{ parameters.authSubscriptionId }}
      workingDirectory: ${{ parameters.TerraformDirectory }}
      backendServiceArm: ${{ parameters.serviceName }}
      backendAzureRmResourceGroupName: ${{ parameters.TerraformStateStorageAccountResourceGroupName }}
      backendAzureRmResourceGroupLocation: ${{ parameters.AzureRegion }}
      backendAzureRmStorageAccountName: ${{ parameters.TerraformStateStorageAccountName }}
      backendAzureRmContainerName: ${{ parameters.TerraformStateStorageAccountContainerName }}
      backendAzureRmKey: ${{ parameters.serviceName }}.tfstate

  - task: TerraformCLI@0
    displayName: 'Terraform : plan'
    inputs:
      command: plan
      environmentServiceName: ${{ parameters.serviceName }}
      providerAzureRmSubscriptionId: ${{ parameters.authSubscriptionId }}
    
    # Deploy the resources
  - task: TerraformCLI@0
    displayName: 'Terraform : apply'
    inputs:
      command: apply
      commandOptions: '-auto-approve'
      environmentServiceName: ${{ parameters.serviceName }}
      providerAzureRmSubscriptionId: ${{ parameters.authSubscriptionId }}
    condition: eq('${{ parameters.rollback }}', false)

    # Rollback deployment by destroying the resources
  - task: TerraformCLI@0
    displayName: 'Terraform : destroy'
    inputs:
      command: apply
      commandOptions: '-destroy'
      environmentServiceName: ${{ parameters.serviceName }}
      providerAzureRmSubscriptionId: ${{ parameters.authSubscriptionId }}
    condition: eq('${{ parameters.rollback }}', true)
```

I've considered suggesting pipelines for other DevOps tools such as GitHub Actions, Bitbucket and GitLab, but I just haven't yet tried to implement those solutions, so wanted to get some feedback on this proposal first.

#### Additional context
:-)
